### ISSUE TITLE
Implement ConcretePath

### ISSUE THREAD

**Issue by jediweon** [ZeroPage/wiki-path-finder#6]
Behold!

**Comment by SkywaveTM** [comment]
implemented in 36633e97d41710b25eaff4206bccb9288c00c737, but has a problem.
```Iterator``` returned by ```ArrayList``` supports ```remove``` method, which can modify the result.

**Comment by kameru** [comment]
It is not intended, but we can solve this problem by make extended iterator that throw UnsupportedOperationException when remove called.

**Comment by kameru** [comment]
#a156256
made UnmodifiableIterator.
